<?php
/**
 * @var \Intern\Chapter45\Block\Adminhtml\ModuleAndStore\CheckModuleAndStore $block
 */
$dt = $block->modulesList();
?>
<p>Hello World!</p>
<div class="dashboard-container row">
    <div class="dashboard-main col-m-6 col-m-push-6">
        <table class="admin__table-secondary">
            <tbody>
            <tr>
                <th>Total number customer:</th>
                <td><?php echo $dt['totalCustomer']; ?></td>
            </tr>
            <tr>
                <th>Total number product:</th>
                <td><?php echo $dt['totalProduct']; ?></td>
            </tr>
            <tr>
                <th>Total number order:</th>
                <td><?php echo $dt['totalOrder']; ?></td>
            </tr>
            <tr>
                <th>Total number invoice:</th>
                <td><?php echo $dt['totalInvoice']; ?></td>
            </tr>
            <tr>
                <th>Total number credit Memo:</th>
                <td><?php echo $dt['totalCreditmemo']; ?></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="dashboard-secondary col-m-6 col-m-pull-6">
        <?php
            echo 'Total number module: '.$dt['totalModule'].'<br>';
            echo 'Total number module non-magento: '.$dt['total_module_non_magento'].'<br>';
        ?>
    </div>
</div>

