<?php
/**
 * Intern
 * Copyright (C) 2020 Intern <info@Intern.com>
 *
 * @package Intern_BuyNow
 * @copyright Copyright (c) 2020 Intern (http://www.Intern.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Intern <info@Intern.com>
 */
?>
<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $helper = $this->helper(\Intern\BuyNow\Helper\Data::class); ?>
<?php $formId = $helper->getAddToCartFormId(); ?>
<?php $buttonTitle = $helper->getButtonTitle() ?>
<div class="buynow-button">
    <button type="submit"
            title="<?= $block->escapeHtml(__($buttonTitle)) ?>"
            id="buy-now"
            class="action primary buy-now-btn"
            data-mage-init='
            {
                "Intern_BuyNow/js/buy-now": {
                    "form": "#<?= $block->escapeHtml($formId); ?>"
                }
            }
            '>
        <span><?= $block->escapeHtml(__($buttonTitle)) ?></span>
    </button>
</div>
