<?php
/**
 * Intern LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.Intern.com/Intern-LICENSE-COMMUNITY.txt
 *
 ********************************************************************
 * @category   Intern
 * @package    Intern_Popup
 * @copyright  Copyright (c) Intern LLC. (http://www.Intern.com)
 * @license    http://store.Intern.com/Intern-LICENSE-COMMUNITY.txt
 */
/** @var $block \Intern\Popup\Block\Popup */
?>
<?php if ($block->isEnabled() && $block->isShow()) : ?>
        <div class="<?= $block->getModalId() ?>-custom-promo-popup no-display">
            <div data-role="loader" class="loading-mask no-display">
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/loader-1.gif') ?>"
                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"/>
                </div>
            </div>

            <div class="page messages no-display">
                <div class="messages"></div>
            </div>

            <form class="<?= $block->getModalId() ?>-form" action="<?= $block->getFormActionUrl() ?>" method="post">
                <div class="content">
                    <?= $block->getContent() ?>
                </div>
            </form>
        </div>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Intern_Popup/js/promo.popup": <?= $block->getJsonConfig() ?>
                }
            }
        </script>
<?php endif;?>

