<style>
    [data-content-type="html"] {
        position: relative;
    }
    .sidebar-main-left, .sidebar-main-right{
        display: inline-block;
        position: absolute;
    }
    .sidebar-main-left{
        left: -280px;
    }
    .sidebar-main-right{
        right: -280px;
    }
</style>
<div class="sidebar sidebar-main-left">
    <img src="<?php echo $this->getData('mediaURL') . $this->getData('sidebarbanner'); ?>"/>
</div>
<div class="sidebar sidebar-main-right">
    <img src="<?php echo $this->getData('mediaURL') . $this->getData('sidebarbanner'); ?>"/>
</div>
