<h1>
    Thông tin phim
</h1>
<table>
    <tr>
        <th>Tên phim</th>
        <th>Mô tả</th>
        <th>Đánh giá</th>
    </tr>
    <?php $datamovie = $block->getDataMovie();

    foreach($datamovie as $value): ?>
    <tr>
        <td>
            <?= $block->escapeHtml($value["name"]) ?>
        </td>
        <td>
            <?= $block->escapeHtml($value["description"]) ?>
        </td>
        <td>
            <?= $block->escapeHtml($value["rating"]) ?>
        </td>
        <td>
            <a href="/datamovie/post/infomovie?movie_id=<?= $block->escapeHtml($value['movie_id']) ?>">
            <button>
                xem đạo diễn, diễn viên
            </button>
            </a>
        </td>
        </tr>
    <?php endforeach; ?>
</table>
