<?php
/**
 * @var \Intern\Chapter45\Block\Infomovie $block
 */
   $dt = $block->getInfoMovie();
   $directorname = $block->getDirectorName();
?>
<h1>Thông tin</h1>
<hr>
<?php if(isset($directorname)){ ?>
<h2>Đạo diễn:</h2>
<p>
    <?php
    echo($directorname);
    ?>
</p>
<?php } ?>
<?php if(isset($dt[0]["name_actor"])){ ?>
<h2>Diễn viên:</h2>
<?php
$dsdv = [];
foreach($dt as $value):
    $dsdv[] = $value["name_actor"];
endforeach;
echo implode ( ', ' , $dsdv);
}
?>.


